### ISSUE TITLE
Name supplied when creating a master is ignored

### ISSUE THREAD

**Issue by ianwalter** [kontena/kontena-plugin-packet#19]
I specified a name at the CLI prompt, but it looks like a name was auto-generated and used instead.

**Comment by kke** [comment]
Yes, the hostname is auto generated, the name you give during creation will be used in the cli's configuration as the master name.

The same thing happens with all providers, but maybe it should be changed at some point.

**Comment by ianwalter** [comment]
When I list masters, the auto-generated name is printed.

**Comment by kke** [comment]
Closed by #34
