### ISSUE TITLE
Prompt ssh-key if no ssh key path given

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena-plugin-packet#30]
Plugin should prompt list of uploaded keys from Packet.net if no ssh key path is given. If path is given then plugin should upload a public key to Packet.net and use that for provisioning.

**Comment by kke** [comment]
Packet adds all your configured ssh keys to the provisioned machine. Selecting one from the list of installed keys is not relevant.

Currently the plugin already uploads the provided ssh key if you provide a path to a keyfile (which defaults to `~/.ssh/id_rsa.pub`)

The sdk has a method for listing installed ssh keys, I think the solution this issue should just prompt for copypaste if  no `--ssh-key` was given and `client.list_ssh_keys.empty?`
